assignment/urls.py
from django.urls import path
# from .views import UserListView
from . import views
from django.conf import settings
from .views import GradeUpdateView, StatusUpdateView


app_name = 'assignment_app'
urlpatterns = [
    path('register_course/<int:pk>/', views.register_course, name='register-course'),
    path('main_dashboard/<int:pk>/', views.main_dashboard, name='main-dashboard'),
    path('assignment/<int:pk>/<int:i_n>/', views.submit_assignment, name='submit-assignment'),
    path('assignment/delete/<int:pk>/<int:i_n>/', views.del_assignment, name='delete-assignment'),
    path('assignment/update/<int:pk>/', views.update_assignment, name='update-assignment'),
    path('assignment/view_assignment_pdf/<int:pk>/', views.viewAssignmentPDF, name='view-assignment-pdf'),
    path('download_assignment/<int:pk>/', views.download_pdf, name='download-file'),
    path('score_student_section/<int:pk>/', views.student_result, name='score-student-section'),
    path('assignment/all_students/<int:pk>/', views.all_students, name='all-students'),
    path('assignment/dashboard/', views.dashboard, name='dashboard'),
    path('assignment/submission_denied/<int:pk>/<int:i_n>/', views.submission_denied, name='submission-denied'),
    path('assignment/score_student_section/update/<int:pk>/', GradeUpdateView.as_view(), name='update-grade'),
    # path('status/update/<int:pk>/', StatusUpdateView.as_view(), name='update-statuses'),
    path('update/<int:pk>/', views.update_submitted, name='update-status'),
    path('view_result/<int:pk>/', views.query_results, name='view-result'),
    path('all_courses/<int:pk>/', views.all_courses, name='all-courses'),
    path('del_courses/<int:pk>/', views.del_course, name='del-course'),
    path('del_upload_file/<int:pk>/', views.del_upload_file, name='del-upload-file'),
    path('student_dashboard/', views.student_dashboard, name='student-dashboard'),
    path('del_choose_course/<int:pk>/', views.del_choose_course, name='del-choose-course'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students_record/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views
from django.contrib.auth import views as auth_views
# from users.views import CustomLoginView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('assignment/', include('assignment.urls', namespace='assignment_app')),
    path('admin/', admin.site.urls),
    path('register_student/', views.register, name='register'),
    path('profile/<int:pk>/<int:i_n>/', views.profile, name='profile'),
    path('back/<int:pk>/', views.back, name='back'),
    path('login_success/', views.login_success, name='login-success'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

# , namespace='assignment-section')
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

users/urls.py
# from django.urls import path
# from . import views
# from django.conf import settings
# from django.contrib.auth import views as auth_views
# from .views import CustomLoginView

# urlpatterns = [
#     path('', views.register, name='register'),
#     path('profile/', views.profile, name='profile'),
#     path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

# ]


# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import JsonResponse
from .forms import (ImageFileUploadForm, FilesForm, StudentResultForm, 
                        StudentResultForm2, UploadedFileForm, 
                        RegisterCourseForm, SemesterForm, SelectCourseForm, StudentOtherCourseForm)
from .models import (Profile, Assignment, StudentResult, 
        UploadedFile, RegisterCourse, Semester, StudentOtherCourse, SelectCourse)
from django.contrib.auth import get_user_model
from django.views.generic import UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import ObjectDoesNotExist
import datetime
import os
import random
from django.conf import settings
from django.http import FileResponse, Http404, HttpResponse, HttpResponseRedirect
from django.utils import timezone
from datetime import datetime as dt
from encrypted_id import ekey
# from users.models import SelectCourse

User = get_user_model()

@login_required
def submit_assignment(request, pk, i_n):
    o_t = StudentOtherCourse.objects.get(id=i_n)
    # user = User.objects.get(pk=o_t.user.pk)
    sel = SelectCourse.objects.get(pk=pk)
    # o_t = StudentOtherCourse.objects.get(choose_course=sel.courses)
    # print(o_t)
    # us = User.objects.filter(course=o_t.choose_course).exclude(index_number=request.user) #filter(course=s_c.courses)
    s = Semester.objects.first()
    rn = random.randint(1, 200)
    date = datetime.date.today()
    if request.method == 'POST':
        form = FilesForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            submission_date = ""
            try:
                u = UploadedFile.objects.filter(course=sel.courses).first()
                submission_date = str(u.date_to_be_subm) # will come from database
            except AttributeError:
                return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(pk,i_n,)))
            curr_date = str(date)
            # if curr_date <= submission_date:
            pdf_file = form.cleaned_data.get('file')
            _, e = os.path.splitext(str(pdf_file))
            if e in ['.pdf', 'txt']:
                assignment = Assignment.objects.create(pdf_file=pdf_file,
                            index=o_t.user.index_number, status='submitted', q_number=rn, date_submitted=date, date_created=timezone.now(), user=o_t.user, studentothercourse=o_t, course=sel.courses)
                return HttpResponseRedirect(reverse('assignment_app:submit-assignment', args=(sel.pk,i_n,)))
            else:
                return JsonResponse({'error': True, 'errors': 'File type('+e+') not supported'})
            # else:
            #     return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(user.pk,)))

    else:
        form = FilesForm()

    ass= Assignment.objects.filter(user=o_t.user).filter(course=o_t.choose_course).order_by('-date_created')
    for a in ass:
        print(a.pk, a.studentothercourse.pk)
    # print(UploadedFile.objects.filter(course=o_t.choose_course))
    context = {
        'assignment': Assignment.objects.filter(user=o_t.user).filter(course=o_t.choose_course).order_by('-date_created'),
        'assigncount': Assignment.objects.filter(user=o_t.user).count(),
        'u_file': UploadedFile.objects.filter(course=sel.courses),
        'c_file': UploadedFile.objects.all(),
        'result': StudentResult.objects.order_by('-date_graded1').filter(course=sel.courses).filter(user=o_t.user),
        'prof': sel.user,
        's': s,
        'sel': sel,
        # 'us': us,
        'o_t': o_t,
     
    }
    
    return render(request, 'assignment/index.html', context)


def query_results(request, pk):
    a = Assignment.objects.get(pk=pk)
    r = StudentResult.objects.filter(q_number=a.q_number)
    print(r)
    return HttpResponseRedirect(reverse('assignment_app:submit-assignment', args=(a.pk,)))



def submission_denied(request, pk, i_n):
    context = {
        'cur_user': pk,   #User.objects.get(pk=pk)
        'i_n': i_n,
    }
    return render(request, 'assignment/submission_denied.html', context)


def dashboard(request):

    if request.user.is_staff or request.user.is_superuser:
        return HttpResponseRedirect(reverse('assignment_app:all-courses', args=(request.user.pk,)))
    return HttpResponseRedirect(reverse('assignment_app:student-dashboard'))

    user = User.objects.get(index_number=request.user.index_number)
    context = {
        'u': user
    }
    return render(request, 'assignment/dashboard.html', context)



@login_required
def del_assignment(request, pk, i_n):
    import os
    
    ass = Assignment.objects.get(pk=pk)
    print(ass.pk)
    o_t = StudentOtherCourse.objects.get(pk=i_n)
    # sel = SelectCourse.objects.get(pk=o_t.)
    date = datetime.date.today()
    submission_date = ''
    try:
        u = UploadedFile.objects.first()
        submission_date = str(u.date_to_be_subm)
    except AttributeError:
        return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(pk,)))
    curr_date = str(date)
    if curr_date <= submission_date:
        f_name = os.path.join(settings.MEDIA_ROOT, str(ass.pdf_file))
        ass.delete()
        os.remove(f_name)
        return HttpResponseRedirect(reverse('assignment_app:submit-assignment', args=(o_t.selectcourse.pk,i_n,)))
    return HttpResponseRedirect(reverse('assignment_app:submission-denied', args=(pk,)))


@login_required
def update_assignment(request, pk):
    ass = get_object_or_404(Assignment, pk=pk)
    form = FilesForm(request.POST or None,
                    request.FILES or None)
    return HttpResponseRedirect(reverse('assignment_app:submit-assignment'))


@login_required
def viewAssignmentPDF(request, pk):
    import os
    from django.conf import settings
    get_file = Assignment.objects.get(pk=pk)
    f_name = os.path.join(settings.MEDIA_ROOT, str(get_file.pdf_file))
    file_name, file_ext = os.path.splitext(f_name)
    if file_ext in ['.pdf', '.txt', '.py']:
        pdf = open(f_name, 'rb').read()
        return HttpResponse(pdf, content_type='application/'+file_ext[1:])


def django_image_and_file_upload_ajax(request):
    if request.method == 'POST':
       form = ImageFileUploadForm(request.POST, request.FILES)
       if form.is_valid():
           form.save()
           
           return JsonResponse({'error': False, 'message': 'Uploaded Successfully'})
       else:
           return JsonResponse({'error': True, 'errors': form.errors})
    else:
        form = ImageFileUploadForm()
        return render(request, 'assignment/upload.html', {'form': form})



def show_files(request):
    obj = Profile.objects.all()
    return render(request, 'assignment/show_files.html', {'object': obj})


@login_required
@staff_member_required
def student_result(request, pk, model_class=StudentResult, form_class=StudentResultForm):
    # user = User.objects.get(pk=pk)
    o_c1 = StudentOtherCourse.objects.get(pk=pk)
    print(o_c1.selectcourse.pk)
    # ass = Assignment.objects.get(pk=pk)
    # print(ass.pk)
    # sel = SelectCourse.objects.get(pk=pk)
    o_c = StudentOtherCourse.objects.filter(user=o_c1.user).filter(choose_course=o_c1.choose_course)
    # sel = SelectCourse.objects.filter(courses=user.course).first()

    try:
        # u = User.objects.get(pk=pk)
        a = Assignment.objects.filter(index=o_c1.user.index_number).first()
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('assignment_app:score-student-section', args=(pk,)))
    if request.method == 'POST':
        form = StudentResultForm(o_c1, request.user, request.POST)
        if form.is_valid:
            obj = form.save(commit=False)
            form.instance.user = o_c1.user
            form.instance.studentothercourse = o_c1
            form.instance.assignment = a
            # update status in assignment
            obj.status = form.cleaned_data.get('status')
            a = Assignment.objects.filter(index=a).update(status=obj.status)
            form.save()

            return HttpResponseRedirect(reverse('assignment_app:score-student-section', args=(pk,)))
    else:
        form = StudentResultForm(o_c1, request.user)
    
    print(o_c1.user.index_number)
    
    s_a = Assignment.objects.order_by('-date_created').filter(course=o_c1.choose_course).filter(user=o_c1.user)
    context = {
        'form': form,
        'ass': s_a,
        'u': o_c1.user,
        'sel': o_c,
        'o_c1': o_c1,
    }
    return render(request, 'assignment/studentresult_update_form.html', context)


@login_required
@staff_member_required
def all_students(request, pk):
    
    all_staff = User.objects.filter(is_staff=True)
    list_all_staff = [s.index_number for s in all_staff]
    user = User.objects.exclude(index_number__in=list_all_staff)
    sel = SelectCourse.objects.get(pk=pk)

    a = Assignment.objects.filter()
    
    o_c = StudentOtherCourse.objects.exclude(user__in=list_all_staff).filter(choose_course=sel.courses) #exclude(user__in=all_staff).
    ie_users = User.objects.exclude(index_number__in=list_all_staff).filter(course=sel.courses)  # #filter(course=s_c.courses)
    query = request.GET.get('q')
    if query:
        ie_users = User.objects.filter(index_number=query)
        ra_users = User.objects.filter(index_number=query)
    if request.method == 'POST':
        form = UploadedFileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            file = form.cleaned_data.get('pdf_file')
            date_to_subm = form.cleaned_data.get('date_to_be_subm')
            date = datetime.date.today()
            # if UploadedFile.objects.count() > 0:
            #     u = UploadedFile.objects.first()
            #     u.pdf_file = file

assignment/templates/assignment/all_courses.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
        <header style="height: 5vh;">
            <nav class="navbar navbar-expand-lg navbar-light bg-info">
                <div style="position: relative; left: 0;">
                    <a class="navbar-brand ml-4 text-white" id="b__fnt" href="#">KNUST</a> |
                    <span style="color: white;"> {{ semester.sem|upper }}</span>
                </div>
                <div id="p__o" style="position: absolute; right: 0;">
                    <a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                </div>

                </div>
            </nav>
        </header>
            <main>
                <div class="all-courses-wrapper">
                    <!-- semester -->
                    <div class="row ml-3 mr-3 pt-2">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body h-20">
                                    <div id="form__wrapper">
                                        <!-- select semester -->
                                        <form method='POST' action=".">{% csrf_token %}
                                            {{ s_form|crispy }}
                                            <button type="submit" class="btn btn-success">Set</button>
                                        </form>
                                        <!-- create course -->
                                        <hr style="background: black;">
                                        <form method='POST' action="." class="pt-2 blck">{% csrf_token %}
                                            <div>{{ c_form|crispy }}</div>
                                            <div>
                                                <button type="submit" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- ------- -->
                    
                    
                <!-- --------------- -->
                    <div class="scrol-vertically mr-4 ml-4">
                        
                        {% for s in a_c %}
                            {% ifchanged %}
                                <div class="vt-card" onclick=location.href="{% url 'assignment_app:all-students' s.pk %}";>
                                    <span id="del__c"><a href="{% url 'assignment_app:del-course' s.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a></span>
                                    <div id="del__v">
                                        {{ s.courses }}
                                        <hr>
                                        <div style="font-size: 17px;">
                                            Number of students 
                                        </div>
                                        <div>{% cal_course s.pk %}</div>
                                    </div>
                                </div>
                            {% endifchanged %}
                        {% endfor %}
                        
                    </div>
                

                <!--  -->

        
                </div>
      
            </main>

        <footer class="ft" style="height: 5vh;">
            <div>
                &copy All rights reserved
            </div>
        </footer>
{% endblock %}

assignment/templates/assignment/all_students.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    

    <!-- ---------------------------- -->
    <div class="all-students-main-wrapper">
        
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-info">
                <a class="navbar-brand ml-4 text-white" id="b__fnt" href="{% url 'assignment_app:all-courses' user.pk %}">{{ sel.courses|upper }}</a><span class="text-white">|</span>
                <a class="navbar-brand ml-4 text-white" id="r__fnt" href="#">{{ semester.sem|upper }}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
                    </li>
                    
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input id="q" name="q" value="{{ request.GET.q }}" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
                </form>
                <div id="p__o">
                    <a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                </div>

                <!-- <div id="l__o">
                    <li class="nav-item dropdown" id="drop">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown" id="all__elements">
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                        </ul>
                    </li>
                </div> -->
                
                </div>
            </nav>
        </header>
        
        <main>
            <div class="container" id="contner">
                <div class="m-pdf-wrapper">
                    <div class="c-pdf-wrapper">
                        <div class="c-s-pdf-wrapper">
                            {% if u_file.count == 0 %}
                                <div id="n__fl">No File(s) Uploaded</div> 
                            {% else %}
                                {% for u in u_file %}
                                    <div class="row pt-1 ml-3 mr-3">
                                        <div class="col-md-12">
                                            <div class="card bg-light" style="position: relative;">
                                                <!-- <i class="fa fa-trash-o" aria-hidden="true"></i> -->
                                                <a class="d-ass" href="#"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
                                                <!-- ------- -->
                                                <div class="d-dialog pl-2">
                                                    <div class="pt-1"><span style="color: orange;">date uploaded:</span> {{ u.date_created }}</div>
                                                    <div><span style="color: orange;">submission date:</span> {{ u.date_to_be_subm }}</div>
                                                    <div class="rem pb-1"><a href="{% url 'assignment_app:del-upload-file' u.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a></div>
                                                </div>
                                                <!-- ------------- -->
                                                <div class="card-body" id="u__wrapper">
                                                <div id="f__name">
                                                        <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                                                        <a href="{% url 'assignment_app:download-file' u.pk %}" target="_new"> <small>{{ u.pdf_file }}</small></a>
                                                </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <!-- --------- -->
                        </div>
                    </div>
                </div>
                
                
               <div class="set-pdf-wrapper mt-1">
                    <div class="row pt-4 ml-3 mr-3 mb-2">
                        <div class="col-md-12">
                            <div class="card bg-success">
                                <div class="card-body text-white">
                                    <form method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" class="btn btn-info">Upload</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="all-student-wrapper">
                    <div class="wrap-all">
                        <div class="st-particular">
                            <div class="particular-wrapper">
                                {% if o_c.count == 0 %}
                                    <div id="n__std">No Student(s) Registered For This Course</div> 
                                {% else %}
                                    {% for all_s in o_c %}
                                        <div class="pt-card">
                                            <div class="im-w">
                                                <img src="{{ all_s.user.userprofile.image.url }}" alt="">
                                            </div>
                                            <div class="indx">{{ all_s.user.index_number }}</div>
                                            <div class="t-st">
                                                <a href="{% url 'assignment_app:submit-assignment' all_s.selectcourse.pk all_s.pk %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                            </div>
                                            <div class="t-sc">
                                                <a href="{% url 'assignment_app:score-student-section' all_s.pk %}"><i class="fa fa-file-text" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        


                        <!-- -------------------- -->
                        <!--<div class="grid-wrappers">
                            <div class="grid-wrappers-two">
                                <div class="ie-h">Integral Equations</div>
                                <div class="ra-h">Real Analysis</div>
                                
                                    
                               
                                    
                                     <div class="ie-wrapper gw">
                                        <div class="ie-main-wrapper">
                                            {% for all_s in ie_users %}
                                                <div class="inc-h">
                                                    <div class="v-card bg-dark">
                                                        <div class="ind">{{ all_s.index_number }}</div>
                                                        <div class="is_l"><a href="{% url 'assignment_app:submit-assignment' all_s.pk %}"><i class="fa fa-eye" aria-hidden="true"></i></a></div>
                                                        <div class="scre"><a href="{% url 'assignment_app:score-student-section' all_s.pk %}"><i class="fa fa-file-text" aria-hidden="true"></i></a></div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    
                              
                                
                                    <div class="ra-wrapper gw">
                                        <div class="ra-main-wrapper">
                                            {% for all_s in ra_users %}
                                                <div class="inc1-h">
                                                    <div class="v-card1 bg-dark">
                                                        <div class="ind">{{ all_s.index_number }}</div>
                                                        <div class="is_l"><a href="{% url 'assignment_app:submit-assignment' all_s.pk %}"><i class="fa fa-eye" aria-hidden="true"></i></a></div>
                                                        <div class="scre"><a href="{% url 'assignment_app:score-student-section' all_s.pk %}"><i class="fa fa-file-text" aria-hidden="true"></i></a></div>
                                                    </div>
                                                </div>
                                            {% endfor %}    
                                        </div>
                                    </div> -->
                               
                            <!-- </div>
                        </div> -->
                            
                    </div>
                </div>

            </div>
        </main>

        <footer class="bg-light text-center">
            <div id="fter">
                &copy; All rights reserved
            </div>
        </footer>
        
    </div>
    
    <script>
        function checkWidth(){
            let w = document.getElementById('f__name');
            w.trunk8()
        }

        checkWidth()
    </script>
{% endblock %}

assignment/templates/assignment/studentresult_update_form.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    <div id="h__w1">
        <div id="h__w">
            
            <div class="b">
                <a href="{% url 'assignment_app:all-students' o_c1.selectcourse.pk %}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
            </div>
            <div class="h">
                <h4>GRADE STUDENT</h4>
            </div>
        </div>
    </div>
   
    <div class="main-wrapper1">
        <div class="students-wrapper">
            <div class="students-items">
                {% for s in ass %}
                    <div class="c-vertical">
                        <h5 id="q__n">Q number: {{ s.q_number }}</h5>
                        <div id="f__wrapp">
                            <div id="p__w">
                                <a href="{% url 'assignment_app:view-assignment-pdf' s.pk %}" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                            </div>
                            <div>
                                <h5 class="dt-c">{{ s.date_created }}</h5>
                            </div>
                            {% if s.status == 'graded' %}
                                <div>
                                    <h5 style="color: green;">{{ s.status }}</h5>
                                </div>
                                <div id="ed">
                                    <a style="color: green;" href="#"><i class="fa fa-check" aria-hidden="true"></i></a>
                                </div>
                            {% else %}
                                <div>
                                    <h5 style="color: red;">{{ s.status }}</h5>
                                </div>
                                <div id="ed">
                                    <a style="color: red;" href="#"><i class="fa fa-check" aria-hidden="true"></i></a>
                                </div>
                            {% endif %}
                            
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <hr style="background-color: honeydew;">
        <form method="POST" action="." enctype="multipart/form-data" id="f__w">{% csrf_token %}
                {{ form|crispy }}
            <div class="form-group" id="b__w">
                <div>
                    <button class="btn btn-outline-info" type="submit">Score student</button>
                </div>
            </div>
        </form>
    </div>
    
{% endblock %}