assignment/urls.py
from django.urls import path
# from .views import UserListView
from . import views
from django.conf import settings
from .views import GradeUpdateView, StatusUpdateView


app_name = 'assignment_app'
urlpatterns = [
    path('register_course/<int:pk>/', views.register_course, name='register-course'),
    path('main_dashboard/<int:pk>/', views.main_dashboard, name='main-dashboard'),
    path('assignment/<int:pk>/<int:i_n>/', views.submit_assignment, name='submit-assignment'),
    path('assignment/delete/<int:pk>/<int:i_n>/', views.del_assignment, name='delete-assignment'),
    path('assignment/update/<int:pk>/', views.update_assignment, name='update-assignment'),
    path('assignment/view_assignment_pdf/<int:pk>/', views.viewAssignmentPDF, name='view-assignment-pdf'),
    path('download_assignment/<int:pk>/', views.download_pdf, name='download-file'),
    path('score_student_section/<int:pk>/', views.student_result, name='score-student-section'),
    path('assignment/all_students/<int:pk>/', views.all_students, name='all-students'),
    path('assignment/dashboard/', views.dashboard, name='dashboard'),
    path('assignment/submission_denied/<int:pk>/<int:i_n>/', views.submission_denied, name='submission-denied'),
    path('assignment/score_student_section/update/<int:pk>/', GradeUpdateView.as_view(), name='update-grade'),
    # path('status/update/<int:pk>/', StatusUpdateView.as_view(), name='update-statuses'),
    path('update/<int:pk>/', views.update_submitted, name='update-status'),
    path('view_result/<int:pk>/', views.query_results, name='view-result'),
    path('all_courses/<int:pk>/', views.all_courses, name='all-courses'),
    path('del_courses/<int:pk>/', views.del_course, name='del-course'),
    path('del_upload_file/<int:pk>/', views.del_upload_file, name='del-upload-file'),
    path('student_dashboard/', views.student_dashboard, name='student-dashboard'),
    path('del_choose_course/<int:pk>/', views.del_choose_course, name='del-choose-course'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students_record/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views
from django.contrib.auth import views as auth_views
# from users.views import CustomLoginView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('assignment/', include('assignment.urls', namespace='assignment_app')),
    path('admin/', admin.site.urls),
    path('register_student/', views.register, name='register'),
    path('profile/<int:pk>/<int:i_n>/', views.profile, name='profile'),
    path('back/<int:pk>/', views.back, name='back'),
    path('login_success/', views.login_success, name='login-success'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

# , namespace='assignment-section')
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

users/urls.py
# from django.urls import path
# from . import views
# from django.conf import settings
# from django.contrib.auth import views as auth_views
# from .views import CustomLoginView

# urlpatterns = [
#     path('', views.register, name='register'),
#     path('profile/', views.profile, name='profile'),
#     path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

# ]


# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth import get_user_model
# from assignment.models import StudentOtherCourse



User = get_user_model()


COURSE_CHOICES = (
                ('', 'Select a course'),
                ('Integral Equations', 'Integral Equations'),
                ('Real Analysis', 'Real Analysis'),
)





# SELECT_COURSE = [(c.courses, c.courses) for c in SelectCourse.objects.all()]  



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='users/profile_pics/default1.png', upload_to='users/profile_pics')

    def __str__(self):
        return f'{self.user.index_number} profile'

users/forms.py
from django import forms
from .models import UserProfile, COURSE_CHOICES
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm, UsernameField
# from assignment.models import SELECT_COURSE
User = get_user_model()

STATUS = (
            ('graded', 'graded'),
             ('not graded', 'graded'),
    )
class UserRegisterForm(UserCreationForm):
    
    # course = forms.ChoiceField(choices=SELECT_COURSE)
    email = forms.EmailField(max_length=150)
    index_number = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('index_number', 'email', 'password1', 'password2',)
      

    def clean_index_number(self, *args, **kwargs):
        index = self.cleaned_data.get('index_number')
        qs = User.objects.filter(index_number=index)
        if qs.exists():
            raise forms.ValidationError("This index number has already been used!")
        return index


    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.index_number = self.cleaned_data['index_number']

        if commit:
            user.save()
            print('Its saved')
        return user
    

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=150)
    index_number = forms.CharField(max_length=150)
    # course = forms.CharField(widget=forms.Select(choices=COURSE_CHOICES), max_length=100)

    class Meta:
        model = User
        fields = ('index_number', 'email',)
        


class UserProfileUpdateForm(forms.ModelForm): 
    class Meta:
        model = UserProfile
        fields = ['image']



# class CustomAuthenticationForm(AuthenticationForm):
#     index_number = UsernameField(
#         label='Index number',
#         widget=forms.TextInput(attrs={'autofocus': True})
#     )

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from .forms import (UserRegisterForm, 
                UserProfileUpdateForm, UserUpdateForm)
from assignment.models import StudentOtherCourse, Assignment, SelectCourse
User = get_user_model()

def register(request):
    if request.method == 'POST':
        u_form = UserRegisterForm(request.POST)
        if u_form.is_valid():
            u_form.save()
            index_number = u_form.cleaned_data.get('index_number')
            index_num = u_form.cleaned_data.get('index')
            messages.success(request, "Registered successfully!!!")
            return HttpResponseRedirect(reverse('login'))
    else:
        u_form = UserRegisterForm()
    context = {
        'u_form': u_form, 
    }
    return render(request, 'users/register.html', context)



@login_required
def profile(request, pk, i_n):
    sel = SelectCourse.objects.get(pk=pk)
    o_t = StudentOtherCourse.objects.get(id=i_n)

    # o_t = StudentOtherCourse.objects.filter(choose_course=sel.courses).first()
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=o_t.user)
        p_form = UserProfileUpdateForm(request.POST, request.FILES, instance=o_t.user.userprofile)
        if u_form.is_valid and p_form.is_valid:
            u_form.save()
            p_form.save()
            messages.success(request, "Profile changed successfully!!!")
            return HttpResponseRedirect(reverse('profile', args=(sel.user.pk,i_n,)))
    else:
        u_form = UserUpdateForm(instance=o_t.user)
        p_form = UserProfileUpdateForm(instance=o_t.user.userprofile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
        'o_t': o_t,    
        'sel': sel,   
    }
    return render(request, 'users/profile.html', context)


def back(request, pk):
    u = User.objects.get(pk=pk)
    return HttpResponseRedirect(reverse('submit-assignment', args=(u.pk,)))

# class CustomLoginView(LoginView):
#     authentication_form = CustomAuthenticationForm


def login_success(request):
    if request.user.is_staff or request.user.is_superuser:
        messages.success(request, "Login successful!!!")
        return HttpResponseRedirect(reverse('assignment-section:all-courses'))
    else:
        messages.success(request, "Login successful!!!")
        return HttpResponseRedirect(reverse('assignment-section:submit-assignment'))

users/templates/users/login.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

    <div id="login__wrapper">
        <div id="login__wrapper2">
            <div class="row bg-dark text-dark" id="t__c">
                <div class="col-md-12 p-4">
                    <div class="card" id="login__box">
                        <div class="card-body w-100">
                            <form method="POST" action=".">{% csrf_token %}
                                <legend class="border-bottom mb-4">Login</legend>
                                {{ form|crispy }}
                            <div class="form-group">
                                <button class="btn btn-outline-info btn-block" type="submit">Sign In</button>
                            </div>
                            </form>
                            <div class="border-top pt-3">
                                <small class="text-muted">Need an account?<a href="{% url 'register' %}" class="ml-2">Sign Up</a></small>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
        

{% endblock %}

users/templates/users/logout.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <!-- <div class="row text-dark">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="logout"> 
                        <h3>You have logged out.<a href="{% url 'login' %}" class="ml-2">Log in</a>again?</h3>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <div class="logout-wrapper">
        <h4>You have logged out.<a href="{% url 'login' %}"> Log in </a>again?</h4>
    </div>
    

{% endblock %}

users/templates/users/profile.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    
    <div class="row" id="user__profile">
        <div class="col-md-12">
            <div class="card">
                <a href="{% url 'assignment_app:submit-assignment' sel.pk o_t.pk %}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
                <div id="t__b">
                    <h5>Profile</h5>
                </div>
                <div class="card-body" id="img__wrapper">
                    <!-- <h1>{{ cur_user }}</h1> -->
                    <div id="i__w">
                        <img src="{{ o_t.user.userprofile.image.url }}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>      
    <!-- ----------- -->
    <div class="main-wrapper"> 
        <div class="row" id="form__wrap">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
                            {{ u_form|crispy }}
                            {{ p_form|crispy }}
                            <hr style="height: 2px;">
                            <div class="form-group" id="btn__wrap">
                                <div>
                                    <button class="btn btn-outline-info" type="submit">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>      
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="main-wrapper"> 
        <div class="row m-4" id="m__wrapper">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action=".">{% csrf_token %}
                            <legend class="border-bottom mb-4">Register</legend>
                            {{ u_form|crispy }}
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Sign Up</button>
                        </div>
                        </form>
                        <div class="border-top pt-3">
                            <small class="text-muted">Already have an account?<a href="{% url 'login' %}" class="ml-2">Sign In</a></small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function refresh(){
            location.reload(true);
        }
        // refresh()
    </script>
{% endblock %}